services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval    : 1s
      timeout: 5s
      retries: 10